version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    networks:
      - app_network
    depends_on:
      - kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
      - app_network
 
  backend:
    build: ./
    ports:
      - "9500:9500"
    depends_on:
      - kafka
    networks:
      - app_network
 
network:
  app_network:
    driver: bridge
    external: true
 