version: '3.8'
 
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app_network
 
  backend:
    build: ./   # adjust if your Dockerfile is elsewhere
    ports:
      - "9500:9500"
    environment:
      PORT : ${PORT}
      MONGO_URI : ${MONGO_URI}
      JWT_SECRET : ${JWT_SECRET}
      KAFKA_BROKERS : ${KAFKA_BROKERS}
      KAFKA_CLIENT_ID : ${KAFKA_CLIENT_ID}
      SMTP_HOST : ${SMTP_HOST}
      SMTP_PORT : ${SMTP_PORT}
      SMTP_USER : ${SMTP_USER}
      SMTP_PASS : ${SMTP_PASS}
      TWILIO_ACCOUNT_SID : ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN : ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM : ${TWILIO_FROM}
      SMS_SENDER_ID : ${SMS_SENDER_ID}
      SMS_API_KEY : ${SMS_API_KEY}
      SMS_CLIENT_ID : ${SMS_CLIENT_ID}
      GITHUB_USER : ${GITHUB_USER}
      GITHUB_TOKEN : ${GITHUB_TOKEN}
      WEBHOOK_URL : ${WEBHOOK_URL}
    depends_on:
      - kafka
    networks:
      - app_network
 
networks:
  app_network:
    driver: bridge
    external: true   # remove this if you haven't manually created the network

 